// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQpK88sn-QUEaR7j02_lqbjahX-2nkGwY',
    appId: '1:947858721632:web:b20072bdd92e2f93eeec05',
    messagingSenderId: '947858721632',
    projectId: 'food-5f010',
    authDomain: 'food-5f010.firebaseapp.com',
    storageBucket: 'food-5f010.appspot.com',
    measurementId: 'G-E3PX3KWL6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG17A9X7jrQ-dUkPrgZKdoFaJY8BL7Ljw',
    appId: '1:947858721632:android:e51491b7db8942f2eeec05',
    messagingSenderId: '947858721632',
    projectId: 'food-5f010',
    storageBucket: 'food-5f010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATi-uiuzyvaCyIJ8QkAJBI5-EHJNIbuP4',
    appId: '1:947858721632:ios:90095eb2340a19d6eeec05',
    messagingSenderId: '947858721632',
    projectId: 'food-5f010',
    storageBucket: 'food-5f010.appspot.com',
    iosBundleId: 'com.example.foody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATi-uiuzyvaCyIJ8QkAJBI5-EHJNIbuP4',
    appId: '1:947858721632:ios:c1ebba4c3b6c1878eeec05',
    messagingSenderId: '947858721632',
    projectId: 'food-5f010',
    storageBucket: 'food-5f010.appspot.com',
    iosBundleId: 'com.example.foody.RunnerTests',
  );
}
